# Generated by Django 5.0.6 on 2024-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_adhaarcarddetail_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhaarcarddetail',
            name='so_do',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
